name: Pomodoro
options:
  bundleIdPrefix: com.bdogellis
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: ""

targets:
  Pomodoro:
    type: application
    platform: iOS
    sources:
      - path: Pomodoro
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      INFOPLIST_FILE: Pomodoro/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bdogellis.pomodoro
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SUPPORTED_INTERFACE_ORIENTATIONS: "UIInterfaceOrientationPortrait"
      SUPPORTED_INTERFACE_ORIENTATIONS_IPAD: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    info:
      path: Pomodoro/Info.plist
      properties:
        CFBundleDisplayName: Pomodoro
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        NSSupportsLiveActivities: true
        NSCalendarsFullAccessUsageDescription: "Pomodoro needs calendar access to schedule study sessions and remind you when they're about to start."
        NSCalendarsUsageDescription: "Pomodoro needs calendar access to schedule study sessions and remind you when they're about to start."
        LSApplicationQueriesSchemes:
          - spotify
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - target: PomodoroWidget
        embed: true
      - target: PomodoroWatch Watch App
        embed: true
    entitlements:
      path: Pomodoro/Pomodoro.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.bdogellis.pomodoro

  PomodoroWatch Watch App:
    type: application
    platform: watchOS
    sources:
      - path: PomodoroWatch
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      INFOPLIST_FILE: PomodoroWatch/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bdogellis.pomodoro.watchkitapp
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      WATCHOS_DEPLOYMENT_TARGET: "10.0"
    info:
      path: PomodoroWatch/Info.plist
      properties:
        CFBundleDisplayName: Pomodoro
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        WKApplication: true
        WKCompanionAppBundleIdentifier: com.bdogellis.pomodoro
    dependencies:
      - target: PomodoroWatchWidget
        embed: true
    entitlements:
      path: PomodoroWatch/PomodoroWatch.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.bdogellis.pomodoro

  PomodoroWatchWidget:
    type: app-extension
    platform: watchOS
    sources:
      - path: PomodoroWatchWidget
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      INFOPLIST_FILE: PomodoroWatchWidget/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bdogellis.pomodoro.watchkitapp.watchwidget
      SKIP_INSTALL: true
      WATCHOS_DEPLOYMENT_TARGET: "10.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: PomodoroWatchWidget/Info.plist
      properties:
        CFBundleDisplayName: Pomodoro Widget
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    entitlements:
      path: PomodoroWatchWidget/PomodoroWatchWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.bdogellis.pomodoro

  PomodoroWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: PomodoroWidget
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      INFOPLIST_FILE: PomodoroWidget/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bdogellis.pomodoro.widget
      SKIP_INSTALL: true
    info:
      path: PomodoroWidget/Info.plist
      properties:
        CFBundleDisplayName: Pomodoro Widget
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    entitlements:
      path: PomodoroWidget/PomodoroWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.bdogellis.pomodoro

schemes:
  Pomodoro:
    build:
      targets:
        Pomodoro: all
        PomodoroWatch Watch App: all
        PomodoroWatchWidget: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
